// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGroupData, GetGroupResponses, PostGroupData, PostGroupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getGroup = <ThrowOnError extends boolean = false>(options: Options<GetGroupData, ThrowOnError>): RequestResult<GetGroupResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetGroupResponses, unknown, ThrowOnError>({ url: '/group', ...options });

export const postGroup = <ThrowOnError extends boolean = false>(options: Options<PostGroupData, ThrowOnError>): RequestResult<PostGroupResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostGroupResponses, unknown, ThrowOnError>({
    url: '/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
