// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGroupData, GetGroupErrors, GetUsersMeData, GetUsersMeResponses, PostGroupData, PostGroupErrors, PostGroupResponses, PostUsersMeRegisterData, PostUsersMeRegisterErrors, PostUsersMeRegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getGroup = <ThrowOnError extends boolean = false>(options: Options<GetGroupData, ThrowOnError>): RequestResult<unknown, GetGroupErrors, ThrowOnError> => (options.client ?? client).get<unknown, GetGroupErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/group',
    ...options
});

export const postGroup = <ThrowOnError extends boolean = false>(options: Options<PostGroupData, ThrowOnError>): RequestResult<PostGroupResponses, PostGroupErrors, ThrowOnError> => (options.client ?? client).post<PostGroupResponses, PostGroupErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postUsersMeRegister = <ThrowOnError extends boolean = false>(options: Options<PostUsersMeRegisterData, ThrowOnError>): RequestResult<PostUsersMeRegisterResponses, PostUsersMeRegisterErrors, ThrowOnError> => (options.client ?? client).post<PostUsersMeRegisterResponses, PostUsersMeRegisterErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>): RequestResult<GetUsersMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUsersMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});
