// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5228/' | (string & {});
};

export type CreateGroupDto = {
    name: string;
    description: string;
    parentGroupId?: null | string;
};

export type GroupListingDto = {
    name: string;
    description: string;
    id?: string;
    created?: string;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type RegisterMeDto = {
    displayName: string;
    biography: string;
};

export type UserDto = {
    userType: UserType;
    displayName?: string;
    biography?: string;
    id?: string;
    created?: string;
};

export type UserType = number;

export type GetGroupData = {
    body?: never;
    path?: never;
    query: {
        skip: number | string;
        limit: number | string;
        parentGroupId?: string;
    };
    url: '/group';
};

export type GetGroupErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type GetGroupError = GetGroupErrors[keyof GetGroupErrors];

export type PostGroupData = {
    body: CreateGroupDto;
    path?: never;
    query?: never;
    url: '/group';
};

export type PostGroupErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostGroupError = PostGroupErrors[keyof PostGroupErrors];

export type PostGroupResponses = {
    /**
     * OK
     */
    200: GroupListingDto;
};

export type PostGroupResponse = PostGroupResponses[keyof PostGroupResponses];

export type PostUsersMeRegisterData = {
    body: RegisterMeDto;
    path?: never;
    query?: never;
    url: '/users/me/register';
};

export type PostUsersMeRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostUsersMeRegisterError = PostUsersMeRegisterErrors[keyof PostUsersMeRegisterErrors];

export type PostUsersMeRegisterResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PostUsersMeRegisterResponse = PostUsersMeRegisterResponses[keyof PostUsersMeRegisterResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];
