// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5228/' | (string & {});
};

export type CreateGroupDto = {
    name: string;
    description: string;
    parentGroupId?: null | string;
};

export type GroupListingDto = {
    name: string;
    description: string;
    id?: string;
    created?: string;
};

export type GetGroupData = {
    body?: never;
    path?: never;
    query: {
        skip: number | string;
        limit: number | string;
        parentGroupId?: string;
    };
    url: '/group';
};

export type GetGroupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostGroupData = {
    body: CreateGroupDto;
    path?: never;
    query?: never;
    url: '/group';
};

export type PostGroupResponses = {
    /**
     * OK
     */
    200: GroupListingDto;
};

export type PostGroupResponse = PostGroupResponses[keyof PostGroupResponses];
