// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCreateGroupDto = z.object({
    name: z.string(),
    description: z.string(),
    parentGroupId: z.string().nullish()
});

export const zGroupListingDto = z.object({
    name: z.string(),
    description: z.string(),
    id: z.string().optional(),
    created: z.iso.datetime().optional()
});

export const zGroupSortDirection = z.int();

export const zHttpValidationProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish(),
    errors: z.record(z.string(), z.array(z.string())).optional()
});

export const zRegisterMeDto = z.object({
    displayName: z.string(),
    biography: z.string()
});

export const zUserType = z.int();

export const zUserDto = z.object({
    userType: zUserType,
    displayName: z.string().optional(),
    biography: z.string().optional(),
    id: z.string().optional(),
    created: z.iso.datetime().optional()
});

export const zGetGroupQuery = z.object({
    Skip: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    Limit: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    ParentGroupId: z.string().optional(),
    Keyword: z.string().optional(),
    SortByCreated: zGroupSortDirection
});

/**
 * OK
 */
export const zGetGroupResponse = z.array(zGroupListingDto);

export const zPostGroupBody = zCreateGroupDto;

/**
 * OK
 */
export const zPostGroupResponse = zGroupListingDto;

export const zPostUsersMeRegisterBody = zRegisterMeDto;

/**
 * OK
 */
export const zPostUsersMeRegisterResponse = zUserDto;

/**
 * OK
 */
export const zGetUsersMeResponse = zUserDto;
